### PR TITLE
Temporary fix for dd exporter publish 400 issue

### LINKED ISSUE #1355: publishe job for 0.34b0 has failed.
Hello,

Publish job for 0.34b0 has failed.

https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/3131270761

### PR DESCRIPTION
**Pull request by srikanthccv**
# Description

The naming of the .tar.gz files used to be separated by - previously but with the new build tool they are _. It used to skip with a warning earlier with a message file already exists https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/2827866155/jobs/4470177468 but it fails now because the naming is mismatching https://github.com/open-telemetry/opentelemetry-python-contrib/actions/runs/3131270761/jobs/5082435841. This is for the package datadog exporter we stopped accepting any changes. adding a skipping step for this exporter (thought already existed) would fix the issue.

Fixes #1355

### CODE REVIEW

File: scripts/build.sh [hunk 1]
```diff
@@ -41,3 +41,6 @@ DISTDIR=dist
    done
  )
 )
+
+# FIXME: This is a temporary workaround.
```
Comment (ocelotl) [inline scripts/build.sh:45]:
```suggestion
# FIXME: This is a temporary workaround, see #1357.
```

**Review by ocelotl — APPROVED** [review]
